pub mod ai;
pub mod bug_hunter;
pub mod capsule;
pub mod context_compiler;
pub mod db;
pub mod demo;
pub mod evidence;
mod git_ignore;
pub mod git_shadow;
pub mod github;
pub mod permissions;
pub mod platform;
pub mod problem;
pub mod project_intelligence;
pub mod recovery;
pub mod redaction;
pub mod repository;
pub mod root_cause;
pub mod runner;
pub mod settings;
pub mod shadow_session;
pub mod state_machine;
pub mod timeline;
pub mod verification;
pub mod workflow;

pub mod project_health;
