import { useMemo, useState } from "react";
import { useI18n } from "../i18n";
import { parseArguments } from "../lib/args";
import { uniqueSessionId } from "../lib/sessionId";
import { bridgeMessage, chooseRepositoryDirectory, invokeTauri } from "../lib/tauri";
import type { RegressionDraft, RepositoryInfo, Session, SessionMeta } from "../types";

function slugify(value: string): string { return value.toLowerCase().trim().replace(/[^a-z0-9а-яё]+/gi, "-").replace(/^-+|-+$/g, "").slice(0,64) || `bug-${Date.now()}`; }
export type VerificationSessionDraft = {
  path: string;
  title: string;
  expected: string;
  actual: string;
  notes: string;
  executable: string;
  args: string;
  expectedExitCode: number;
  handoff?: {
    caseId: string;
    hypothesisId: string;
    experimentId: string;
    regressions: RegressionDraft[];
  };
};
type Props = { onClose: () => void; onComplete: (sessionId: string) => Promise<void> | void; initialPath?: string; initialDraft?: VerificationSessionDraft | null; presenceClass?: string };
export function NewSessionWizard({ onClose, onComplete, initialPath = "", initialDraft = null, presenceClass = "open" }: Props) {
  const { t } = useI18n();
  const labels = [t("wizard.repository"),t("wizard.problem"),t("wizard.reproduction"),t("wizard.criterion"),t("wizard.review")];
  const [step,setStep]=useState(0), [repoPath,setRepoPath]=useState(initialDraft?.path ?? initialPath), [repo,setRepo]=useState<RepositoryInfo|null>(null), [title,setTitle]=useState(initialDraft?.title ?? ""), [sessionId,setSessionId]=useState(""), [expected,setExpected]=useState(initialDraft?.expected ?? ""), [actual,setActual]=useState(initialDraft?.actual ?? ""), [notes,setNotes]=useState(initialDraft?.notes ?? ""), [executable,setExecutable]=useState(initialDraft?.executable ?? ""), [argsInput,setArgsInput]=useState(initialDraft?.args ?? ""), [expectedExitCode,setExpectedExitCode]=useState(String(initialDraft?.expectedExitCode ?? 0)), [error,setError]=useState<string|null>(null), [busy,setBusy]=useState(false);
  const [handoffRegressions, setHandoffRegressions] = useState<RegressionDraft[]>(initialDraft?.handoff?.regressions ?? []);
  const args = useMemo(() => { try { return parseArguments(argsInput); } catch { return []; } }, [argsInput]);
  async function browseRepository(){ setError(null); try { const selected=await chooseRepositoryDirectory(t("dialog.chooseRepo")); if(selected){setRepoPath(selected);setRepo(null);} } catch(e){setError(bridgeMessage(e));} }
  async function validateRepository(){ setBusy(true);setError(null); try{setRepo(await invokeTauri<RepositoryInfo>("inspect_repository",{path:repoPath.trim()}));setStep(1);}catch(e){setError(bridgeMessage(e));}finally{setBusy(false);} }
  function continueProblem(){ if(!title.trim()){setError(t("wizard.titleField"));return;} if(!expected.trim()||!actual.trim()){setError(`${t("wizard.expected")} / ${t("wizard.actual")}`);return;} if(!sessionId.trim())setSessionId(slugify(title));setError(null);setStep(2); }
  function continueCommand(){ if(!executable.trim()){setError(t("wizard.executable"));return;} try{parseArguments(argsInput);}catch(e){setError(e instanceof Error?e.message:t("common.invalidArguments"));return;}setError(null);setStep(3); }
  async function createSession(){ if(!repo)return; const requestedId=(sessionId.trim()||slugify(title)).slice(0,96);const exitCode=Number(expectedExitCode);if(!Number.isInteger(exitCode)){setError(t("wizard.expectedExit"));return;}setBusy(true);setError(null);try{const existing=await invokeTauri<Session[]>("list_sessions");const id=uniqueSessionId(requestedId,existing.map(item=>item.id));if(id!==sessionId)setSessionId(id);const meta:SessionMeta={title:title.trim(),expected:expected.trim(),actual:actual.trim(),notes:notes.trim()};await invokeTauri<Session>("create_bug_session",{id,meta});await invokeTauri<RepositoryInfo>("attach_repository",{sessionId:id,path:repo.path});await invokeTauri("add_reproduction_step",{sessionId:id,executable:executable.trim(),args:parseArguments(argsInput),expectedExitCode:exitCode});await invokeTauri("capture_environment",{sessionId:id});await invokeTauri("create_shadow_workspace",{sessionId:id});if(initialDraft?.handoff){await invokeTauri("stage_investigation_verification",{sessionId:id,caseId:initialDraft.handoff.caseId,hypothesisId:initialDraft.handoff.hypothesisId,experimentId:initialDraft.handoff.experimentId,regressions:handoffRegressions});}await onComplete(id);}catch(e){setError(bridgeMessage(e));}finally{setBusy(false);} }
  return <div className={`modal-layer presence-${presenceClass}`} role="presentation"><section className="wizard" role="dialog" aria-modal="true" aria-labelledby="wizard-title"><header className="wizard-header"><div><h2 id="wizard-title">{t("wizard.title")}</h2><p>{t("wizard.subtitle")}</p></div><button className="icon-close" onClick={onClose} disabled={busy} aria-label={t("common.close")}>×</button></header><div className="wizard-progress" aria-label="Progress">{labels.map((label,index)=><div key={label} className={index===step?"current":index<step?"done":""}><span>{index+1}</span><small>{label}</small></div>)}</div><div className="wizard-body">
    {step===0&&<><div className="field"><label>{t("wizard.repository")}</label><div className="path-picker"><input autoFocus value={repoPath} onChange={e=>{setRepoPath(e.target.value);setRepo(null);}} placeholder="C:\\Projects\\my-app"/><button className="button" onClick={()=>void browseRepository()} disabled={busy}>{t("common.browse")}</button></div><p>{t("wizard.repoHelp")}</p></div>{repo&&<div className="repo-preview"><strong>{repo.path}</strong><span>{repo.branch} · {repo.head_commit.slice(0,8)} · {repo.is_dirty?`${repo.changed_files.length} ${t("top.localChanges")}`:t("common.clean")}</span></div>}</>}
    {step===1&&<div className="form-stack"><div className="field"><label>{t("wizard.titleField")}</label><input autoFocus value={title} onChange={e=>{setTitle(e.target.value);if(!sessionId)setSessionId(slugify(e.target.value));}}/></div><div className="field"><label>{t("wizard.sessionId")}</label><input value={sessionId} onChange={e=>setSessionId(slugify(e.target.value))}/></div><div className="field"><label>{t("wizard.expected")}</label><textarea value={expected} onChange={e=>setExpected(e.target.value)}/></div><div className="field"><label>{t("wizard.actual")}</label><textarea value={actual} onChange={e=>setActual(e.target.value)}/></div><div className="field"><label>{t("wizard.notes")} <span>{t("common.optional")}</span></label><textarea value={notes} onChange={e=>setNotes(e.target.value)}/></div></div>}
    {step===2&&<div className="form-stack"><div className="field"><label>{t("wizard.executable")}</label><input autoFocus value={executable} onChange={e=>setExecutable(e.target.value)} placeholder="npm"/><p>{t("wizard.executableHelp")}</p></div><div className="field"><label>{t("wizard.arguments")}</label><input value={argsInput} onChange={e=>setArgsInput(e.target.value)} placeholder="test -- auth"/></div><div className="command-preview"><span>{t("wizard.command")}</span><code>{[executable||"…",...args].join(" ")}</code></div></div>}
    {step===3&&<div className="criterion-card"><h3>{t("wizard.criterionTitle")}</h3><p>{t("wizard.criterionHelp")}</p><div className="field compact-field"><label>{t("wizard.expectedExit")}</label><input autoFocus inputMode="numeric" value={expectedExitCode} onChange={e=>setExpectedExitCode(e.target.value)}/></div><div className="before-after-explainer"><div><span>{t("overview.before")}</span><strong>{t("wizard.beforeHelp")}</strong><small>{t("wizard.beforeSmall")}</small></div><div className="arrow">→</div><div><span>{t("overview.after")}</span><strong>{t("wizard.afterHelp")}</strong><small>{t("wizard.afterSmall")}</small></div></div></div>}
    {step===4&&<><div className="review-grid"><section><h3>{t("wizard.repository")}</h3><p className="mono-wrap">{repo?.path}</p><small>{repo?.branch} · {repo?.head_commit.slice(0,8)}</small></section><section><h3>{t("wizard.problem")}</h3><p>{title}</p><small>{sessionId||slugify(title)}</small></section><section><h3>{t("wizard.reproduction")}</h3><code>{[executable,...args].join(" ")}</code><small>exit {expectedExitCode}</small></section><section><h3>{t("wizard.isolation")}</h3><p>{initialDraft?.handoff?t("wizard.transferredPatch"):t("wizard.newWorktree")}</p><small>{initialDraft?.handoff?t("wizard.transferredPatchHelp"):t("wizard.isolationHelp")}</small></section></div>{initialDraft?.handoff&&handoffRegressions.length>0&&<section className="wizard-regressions"><header><h3>{t("verification.regressionContract")}</h3><p>{t("verification.regressionContractHelp")}</p></header>{handoffRegressions.map(check=><div key={check.stable_id}><span><strong>{check.title}</strong><code>{[check.executable,...check.args].join(" ")}</code></span><span>{t(`regressionLevel.${check.level}`)}{check.level!=="Required"&&<button className="button ghost small" onClick={()=>setHandoffRegressions(items=>items.map(item=>item.stable_id===check.stable_id?{...item,level:"Required"}:item))}>{t("verification.makeRequired")}</button>}</span></div>)}</section>}</>}
    {error&&<div className="form-error">{error}</div>}
  </div><footer className="wizard-footer"><button className="button ghost" onClick={()=>step===0?onClose():setStep(v=>v-1)} disabled={busy}>{step===0?t("common.cancel"):t("common.back")}</button>{step===0&&<button className="button primary" onClick={()=>void validateRepository()} disabled={busy||!repoPath.trim()}>{busy?t("wizard.checking"):t("common.continue")}</button>}{step===1&&<button className="button primary" onClick={continueProblem}>{t("common.continue")}</button>}{step===2&&<button className="button primary" onClick={continueCommand}>{t("common.continue")}</button>}{step===3&&<button className="button primary" onClick={()=>setStep(4)}>{t("common.review")}</button>}{step===4&&<button className="button primary" onClick={()=>void createSession()} disabled={busy}>{busy?t("wizard.preparing"):t("wizard.create")}</button>}</footer></section></div>;
}
